name: "Multi Event Pipeline / Workflow"

on:
    push:
        branches:
            - master
            - demo
    schedule:
        - cron: "0 1 30 7 *"  # Runs daily at midnight UTC
    pull_request:
        branches:
            - master
        types:
            - closed
            - opened

    workflow_dispatch: 
    

jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on master/demo push"
              run: echo "Running on master/demo push"

    on-pull-request:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request"
              run: echo "Running on pull request" 

    on-pull-request-opened:
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request opened"
              run: echo "Running on pull request opened"

    on-pull-request-closed:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request closed"
              run: echo "Running on pull request closed"



    on-workflow-dispatch:
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on workflow dispatch"
              run: echo "Running on workflow dispatch"

    on-schedule:
        if: github.event_name == 'schedule'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on schedule"
              run: echo "Running on schedule event"